name: My First Action

on:
    push:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Get my code
              uses: actions/checkout@v4

            - name: Say hello
              run: echo "Hello from GitHub Actions!"
